<a href="https://colab.research.google.com/github/satishilluri2/git1/blob/kits/data_preprocessing_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#step 1 we have to import the data from csv file 
#pip install pandas
import pandas as pd
data= pd.read_csv("Data.csv")
data.head()


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
data.columns


Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [ ]:
data["Age"][6]

nan

In [ ]:
data.keys()

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [ ]:
data.head(5)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
data.tail(
)

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
data.tail()

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

#STEP 2: SEPARATE BOTH I/P & O/P

In [ ]:
#step-2: Now we have to seperate the both input and output varibles
#Independent Varables
X = data.iloc[:,0:-1].values
Y=data.iloc[:,-1,].values


#STEP-*3* : HANDLE MISSING DATA

In [ ]:
#Step-3:TALK ABOUT MISSING DATA
from sklearn.impute import SimpleImputer
import numpy as np
imputer= SimpleImputer(missing_values = np.nan,strategy="mean")
X[:,1:3] = imputer.fit_transform(X[:,1:3])


In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)


# Step:4 TAKING CARE OF STRING DATA


In [ ]:
#independent values X at index 0
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[0])],remainder="passthrough")
X = ct.fit_transform(X)
print(X)



[[0.0 1.0 0.0 1.0 -1.2247448713915892 1.2247448713915892 0.0 0.0 44.0
  72000.0]
 [1.0 0.0 1.0 0.0 0.8164965809277261 -0.8164965809277261 0.0 1.0 27.0
  48000.0]
 [1.0 0.0 1.0 0.0 0.8164965809277261 -0.8164965809277261 1.0 0.0 30.0
  54000.0]
 [1.0 0.0 1.0 0.0 0.8164965809277261 -0.8164965809277261 0.0 1.0 38.0
  61000.0]
 [1.0 0.0 1.0 0.0 0.8164965809277261 -0.8164965809277261 1.0 0.0 40.0
  63777.77777777778]
 [0.0 1.0 0.0 1.0 -1.2247448713915892 1.2247448713915892 0.0 0.0 35.0
  58000.0]
 [1.0 0.0 1.0 0.0 0.8164965809277261 -0.8164965809277261 0.0 1.0
  38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 -1.2247448713915892 1.2247448713915892 0.0 0.0 48.0
  79000.0]
 [1.0 0.0 1.0 0.0 0.8164965809277261 -0.8164965809277261 1.0 0.0 50.0
  83000.0]
 [0.0 1.0 0.0 1.0 -1.2247448713915892 1.2247448713915892 0.0 0.0 37.0
  67000.0]]


In [ ]:
# Encode the dependent variable
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [ ]:
Y


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

#STEP 5:FEATURE SCALING

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X[:,3:5] = sc.fit_transform(X[:,3:5])


In [ ]:
X


array([[1.0, 0.0, 1.0, -1.2247448713915892, 1.2247448713915892, 0.0, 0.0,
        44.0, 72000.0],
       [0.0, 1.0, 0.0, 0.8164965809277261, -0.8164965809277261, 0.0, 1.0,
        27.0, 48000.0],
       [0.0, 1.0, 0.0, 0.8164965809277261, -0.8164965809277261, 1.0, 0.0,
        30.0, 54000.0],
       [0.0, 1.0, 0.0, 0.8164965809277261, -0.8164965809277261, 0.0, 1.0,
        38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.8164965809277261, -0.8164965809277261, 1.0, 0.0,
        40.0, 63777.77777777778],
       [1.0, 0.0, 1.0, -1.2247448713915892, 1.2247448713915892, 0.0, 0.0,
        35.0, 58000.0],
       [0.0, 1.0, 0.0, 0.8164965809277261, -0.8164965809277261, 0.0, 1.0,
        38.77777777777778, 52000.0],
       [1.0, 0.0, 1.0, -1.2247448713915892, 1.2247448713915892, 0.0, 0.0,
        48.0, 79000.0],
       [0.0, 1.0, 0.0, 0.8164965809277261, -0.8164965809277261, 1.0, 0.0,
        50.0, 83000.0],
       [1.0, 0.0, 1.0, -1.2247448713915892, 1.2247448713915892, 0.0, 0.0,
        37.0, 67000.0

#Step 6: Splitting the data into train and test

In [ ]:
from sklearn.model_selection import train_test_split
X_train ,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)


In [ ]:
Y_test


array([1, 1])